#!/usr/bin/env tsx
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

// ES module equivalent of __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Import methodology modules
import { ADVANCE_MODE, LIGHT_MODE } from '../src/methodology/index.js';

const AUTO_GENERATED_WARNING = `<!--
  ⚠️  AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY

  This file is automatically generated from the TypeScript source:
  - Advance mode: src/methodology/advance.ts
  - Light mode: src/methodology/light.ts

  To update this methodology:
  1. Edit the TypeScript source file
  2. Run: npm run methodology:validate
  3. Run: npm run methodology:generate
  4. Test all integrations
  5. Commit changes
-->

`;

async function generateDocs() {
  const rootDir = path.join(__dirname, '..');

  console.log('📝 Generating methodology documentation...\n');

  // Generate Advance mode markdown for Claude Code skill
  const advanceMarkdown = `${AUTO_GENERATED_WARNING}# Prompt Enhancement Methodology

This document contains the comprehensive framework for transforming basic prompts into production-grade, optimized prompts that maximize AI performance and accuracy.

---

${ADVANCE_MODE.systemInstruction}
`;

  // Generate Light mode markdown for Claude Code skill
  const lightMarkdown = `${AUTO_GENERATED_WARNING}# Prompt Enhancement Methodology - Light Version

A streamlined enhancement framework for quick prompt optimization.

**Target**: ${LIGHT_MODE.targetTokens}

---

${LIGHT_MODE.systemInstruction}
`;

  // Paths for generated files
  const files = [
    {
      path: path.join(
        rootDir,
        '.claude/skills/prompt-boost/METHODOLOGY.md'
      ),
      content: advanceMarkdown,
      name: 'Claude Code Skill - Advance Mode',
    },
    {
      path: path.join(
        rootDir,
        '.claude/skills/prompt-boost/METHODOLOGY-LIGHT.md'
      ),
      content: lightMarkdown,
      name: 'Claude Code Skill - Light Mode',
    },
    {
      path: path.join(rootDir, '.cursor/commands/prompt-boost-advanced.md'),
      content: ADVANCE_MODE.systemInstruction,
      name: 'Cursor Command - Advance Mode',
    },
    {
      path: path.join(rootDir, '.cursor/commands/prompt-boost-lite.md'),
      content: LIGHT_MODE.systemInstruction,
      name: 'Cursor Command - Light Mode',
    },
  ];

  // Write all files
  for (const file of files) {
    try {
      await fs.writeFile(file.path, file.content, 'utf-8');
      console.log(`✅ Generated: ${file.name}`);
      console.log(`   → ${path.relative(rootDir, file.path)}`);
    } catch (error) {
      console.error(`❌ Failed to generate: ${file.name}`);
      console.error(`   Error: ${error.message}`);
      process.exit(1);
    }
  }

  console.log('\n✨ All methodology documentation generated successfully!');
  console.log('\n📊 Summary:');
  console.log(`   - Advance Mode: ${ADVANCE_MODE.systemInstruction.length} characters`);
  console.log(`   - Light Mode: ${LIGHT_MODE.systemInstruction.length} characters`);
  console.log(`   - Target tokens: Advance ${ADVANCE_MODE.targetTokens}, Light ${LIGHT_MODE.targetTokens}`);
}

// Run the generator
generateDocs().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});
